services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports: 
      - "8300:8300"
    volumes:
      - /home/json/.secrets/gdsc/creds.json:/creds.json
      - /home/json/production/gdsc/log-format.yml:/log-format.yml
      - /home/json/production/logs/gdsc/:/logs
  
  client:
    env_file:
      - ./front-end/.env.local
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8301:3000"
    depends_on:
      - backend

  server:
    build:
      context: ./peer-to-peer
      dockerfile: Dockerfile
    ports:
      - 8302:7093
